### PR TITLE
Add IsRecurring to marketing promo context

### PR DESCRIPTION
**Pull request by benb1n**
I have a client that has requested marketing cart promotions related to whether a new order from the storefront is a subscription or not (i.e., has a payment plan). I added the necessary change to this module, and I have more changes ready to send a PR for the changes to vc-module-dynamic-expressions. I'll send those once I hear back on this PR. Let me know if the name `IsRecurring` works or if you have any further suggestions. @tatarincev

### CODE REVIEW

**Comment by benb1n** [comment]
@tatarincev As a follow up to this, I think I'll need a way to track recurring products in the cart too. Right now, our client only uses cart-level payment plans, but we're talking about using product-level payment plans, so the marketing context would need to give enough information to evaluate that and the rewards would likely also need changes to support applying subscription discounts to only the subscription items in the cart (so they can have a cart mixed with recurring and non-recurring items).

**Comment by tatarincev** [comment]
@benb1n Sory for the delay with review, I think it makes sense to add `IsReccuring` to the `ProductPromoEntry` as well.

**Comment by benb1n** [comment]
@tatarincev Thanks! I'll submit another PR for that change soon.

**Comment by benb1n** [comment]
Added PR #150

**Comment by yecli** [comment]
Released: https://github.com/VirtoCommerce/vc-module-core/releases/tag/v2.25.33

**Pull request merged**
