### PR TITLE
Pricing module UX improvements #40

### PR DESCRIPTION
**Pull request by andrey-ciclicci**
Added "IPricingService.DeletePricelistsAssignmentsByFilter" definition

### CODE REVIEW

**Comment by yecli** [comment]
Probably we need to add new method to IPricingSearchService to avoid cyclic dependencies, as we want to use search and IPricingSearchService already uses IPricingService.

**Comment by andrey-ciclicci** [comment]
> Probably we need to add new method to IPricingSearchService to avoid cyclic dependencies, as we want to use search and IPricingSearchService already uses IPricingService.

Both IPricingSearchService.cs and IPricingService.cs use the same 'VirtoCommerce.Domain.Pricing.Model' and 'VirtoCommerce.Domain.Pricing.Model.Search' dependencies. No compiler errors or warnings have appeared. Is it ok to leave it this way?

**Comment by yecli** [comment]
I think no, as this leads to a tight coupling between services (static IPricingSearchService method usage in IPricingService), which is not good at my opinion.

**Comment by andrey-ciclicci** [comment]
> I think no, as this leads to a tight coupling between services (static IPricingSearchService method usage in IPricingService), which is not good at my opinion.

Should we add a helper solution for both implementations? Concerned a bit of putting remove method in search class.

**Comment by yecli** [comment]
Really, maybe some extension for IQueryable<PricelistAssignment> like BuildSearchQuery could be helpful.

**Comment by andrey-ciclicci** [comment]
> Really, maybe some extension for IQueryable<PricelistAssignment> like BuildSearchQuery could be helpful.

Followed the advice, updated vc-module-pricing and added an IQueryable extension.

**Comment by andrey-ciclicci** [comment]
Important: a 'VirtoCommerce.Domain' nuget package should be built in _vc-module-core_ to use the updated IPricingService in _vc-module-pricing_.

**Pull request closed without merging**
