### PR TITLE
VP-3127: Set relative iconUrl

### PR DESCRIPTION
**Pull request by eMazeika**
https://virtocommerce.atlassian.net/browse/VP-3127

### CODE REVIEW

**Comment by Woland2k** [comment]
Do we need reviews for such checkin? @eMazeika, can you simply merge it and push the change to master branch for it to be released?

**Comment by eMazeika** [comment]
@Woland2k, "not authorized to merge this pull request"

**Comment by Woland2k** [comment]
@eMazeika please make sure you're authorized and you should be able to merge it to master branch as well

**Comment by eMazeika** [comment]
ok, I got elevated permissions, thanx

**Pull request merged**
