### PR TITLE
Search ConnectionString defined in the Platform settings should override Web.config based value

### PR DESCRIPTION
**Pull request by miguelhasse**

### CODE REVIEW

**Comment by artem-dudarev** [comment]
It should not.
The web.config vaue has higher priority intentionally - to allow managing connection strings through the Azure portal.

**Comment by lusocoding** [comment]
I have to agree with @miguelhasse on this one.

The web config should have the default values and they should be overridden by the configuration on the platform. Also, it may be that the admin of the platform is not an admin on azure, so the only way he has to override configurations would be to configure them directly on the platform.

If web config overrides the platform configuration then all the inputs on the platform doesn't really make much sense.

**Comment by artem-dudarev** [comment]
Azure admin is more powerful than a platform admin.
Platform admin should not be able to change settings configured by Azure admin.
Actually settings overriden by web.config or Azure portal should be read-only. I've created an issue for this improvement:
https://github.com/VirtoCommerce/vc-platform/issues/1002

**Comment by OlegoO** [comment]
Our strategy that connection string in web.config has high priority and should be configured by IT

**Pull request closed without merging**
