### PR TITLE
Catch errors during scale-out indexation.

### PR DESCRIPTION
**Pull request by WimVergouwe**
Errors during scale-out indexation are not handled correctly because the tasks are not awaited.
(I'm sorry, my bad)

### CODE REVIEW

**Comment by WimVergouwe** [comment]
@artem-dudarev, I'm not quite sure about the problem you have with multiple returns, so I used the ternary operator.

**Comment by asvishnyakov** [comment]
@WimVergouwe It's just (our) best practice: you must have only single point of exit from function

**Comment by artem-dudarev** [comment]
you don't need to return a task:
```
public async Task IndexDocumentsHighPriorityAsync(string documentType, string[] documentIds)
{
    if(!documentIds.IsNullOrEmpty())
    {
        await _indexingManager.IndexDocumentsAsync(documentType, documentIds);
    }
}
```

**Comment by WimVergouwe** [comment]
@artem-dudarev , do you still need anything from me to complete this PR?

**Comment by artem-dudarev** [comment]
@WimVergouwe, No, I've approved the PR 9 days ago.

**Comment by asvishnyakov** [comment]
@tatarincev Merge PR please

**Pull request merged**
