### PR TITLE
Add AssociationObjectId

### PR DESCRIPTION
**Pull request by weimin-kooboo**
Obtain the product containing the association by the associated object id

### CODE REVIEW

**Comment by tatarincev** [comment]
@weimin-kooboo  Dou you know what you can extend any of SearchCriteria with your own types?
If we added this property to ProductSearchCriterie we should also extend our default product search services to use this property in the search.

**Comment by weimin-kooboo** [comment]
what's the mean "you can extend any of SearchCriteria with your own types"?
we have implemented this function ,contain vc-module-catalog and vc-module-core ,we will pull request together if you want

**Comment by ruyi-kooboo** [comment]
Hi,@tatarincev,Can you give us a demo about how to extend SearchCriteria?

**Comment by tatarincev** [comment]
Just  call this line of code in PostInitialize method in the your module.cs
``` AbstractTypeFactory<ProductSearchCriteria>.OverrideType<ProductSearchCriteria, ProductSearchCriteria2>();```

**Comment by ruyi-kooboo** [comment]
Thank you very much, we will try your suggested method

**Pull request closed without merging**
